runtime: go114

main: ./cmd

env_variables:
  SERVER_HOST=127.0.0.1
  SERVER_PORT=4483
  INSTANCE_NAME=wide-episode-286220:asia-east2:taxa-p0c
  DBUSER=taxa-p0c
  DBPASS=taxap0c1234
  DBNAME=taxa-p0c
  SSLMODE_ENABLED=disable
  DBPORT=5432
  LOGGING_STATUS=true
  GIN_MODE=release

