// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type FarmInput struct {
	ID        string `json:"id"`
	Size      string `json:"size"`
	Soil      string `json:"soil"`
	ImageHash string `json:"imageHash"`
	Season    string `json:"season"`
	Owner     string `json:"owner"`
}
