// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/99designs/gqlgen/graphql"
)

type AddressInput struct {
	PostalCode   string `json:"postalCode"`
	StreetName   string `json:"streetName"`
	City         string `json:"city"`
	RestaurantID string `json:"restaurantID"`
}

type Cords struct {
	Lon float64 `json:"lon"`
	Lat float64 `json:"lat"`
}

type DishInput struct {
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Price       float64        `json:"price"`
	Image       graphql.Upload `json:"image"`
	AddOns      []string       `json:"addOns"`
	MenuID      string         `json:"menuId"`
}

type DishNote struct {
	DishID      string   `json:"dishId"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	AddOns      []string `json:"addOns"`
	Price       float64  `json:"price"`
	Count       int      `json:"count"`
	Subtotal    float64  `json:"subtotal"`
}

type MenuInput struct {
	MenuHeadline string `json:"menuHeadline"`
	RestaurantID string `json:"restaurantId"`
}

type OrderInput struct {
	OrderNotes      []*DishNote `json:"orderNotes"`
	RestaurantNotes string      `json:"restaurantNotes"`
	RestaurantID    string      `json:"restaurantId"`
}

type RestaurantInput struct {
	RestaurantName string `json:"restaurantName"`
	About          string `json:"about"`
	Telephone      string `json:"telephone"`
}

type UploadLicense struct {
	RestaurantID string         `json:"restaurantID"`
	File         graphql.Upload `json:"file"`
}
